version: "3.9"

services:

  django:
     container_name: "django"
     build: ./lab3
     command: sh -c "python manage.py runserver 0.0.0.0:8000"
     ports:
        - "8000:8000"
     restart: unless-stopped

  nginx:
     build:
       context: ./nginx
     ports:
       - "80:80"
     environment:
       - NGINX_PORT=80
     depends_on:
       - django